# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PNPM_CACHE_FOLDER: .pnpm-store

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:

      matrix:

        os: [ubuntu-latest, windows-latest, macos-latest]
  # This workflow contains a single job called "build"
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: setup caching
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: install dependencies
        run: pnpm install

      - name: build packages
        run: pnpm build

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

      - name: run tests
        run: pnpm test
        # run coverage only on ubuntu
      - name: Coveralls
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info